### ISSUE TITLE
Problems building the lib

### ISSUE THREAD

**Issue by mkae** [KimuraRyo/libbsdf#1]
Hi!

I am trying to build this lib and run into trouble with making CMake find everything.

`eigen3` is installed: 

```
$ cmake --find-package -DNAME=eigen3 -DCOMPILER_ID=CLANG -DLANGUAGE=CXX -DMODE=EXIST -DCMAKE_MODULE_PATH=/opt/local/share/cmake/Modules ..
eigen3 found.
```

but the above command doesn't create a makefile in the respective build folder.

If I run it without the `--find-package` option cmake fails to find the lib:

```
$ cmake ..
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/marko/WC/GIT/libbsdf/build/CMakeFiles/CMakeOutput.log".
```

Any hints?

I've tried this on a late-2009 iMac with OSX 10.10 and MacPorts for installing `eigen3`.

**Comment by KimuraRyo** [comment]
Hi,

I fixed CMakeLists.txt for MacPorts. Please pull the libbsdf repository. You need to add `EIGEN3_INCLUDE_DIR` and set the path to the include directory of Eigen3.

**Comment by mkae** [comment]
Hi Ryo,

thanks very much for your fixes. `libbsdf` now built successfully:

```
In file included from /Users/marko/WC/GIT/libbsdf/include/libbsdf/Brdf/SampleSet.h:14:
/Users/marko/WC/GIT/libbsdf/include/libbsdf/Common/Array.h:63:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto it = srcArray.begin(); it != srcArray.end(); ++it, ++i) {
         ^
1 warning generated.
[100%] Linking CXX static library liblibbsdf.a
[100%] Built target libbsdf
```

but still shows C++11 warnings here on my end. Hmmm, shouldn't this C++11 thingy be handled by cmake itself, or do I need to install another compiler to get this to work?

Thanks,
Marko

**Comment by KimuraRyo** [comment]
Hi Marko,

I currently use Xcode Version 7.2.1, and the C++11 warning isn't shown. -std=c++11 may be suitable as the option of compile.

**Comment by mkae** [comment]
Hi Ryo,

same here. Which OSX version are you running on your end?

Where should I specify the option? Can I pass that on to cmake?

(I haven't come up with a Portfile for this project up to now. In there I could add the option easily, but I have no clue how to do that on the command line now, since `cmake; make` is all I am doing so far.

BTW, please check your [BSDFViewer project](https://github.com/KimuraRyo/BSDFViewer), as I have a pull request created just now.

**Comment by KimuraRyo** [comment]
Hi Marko,

I'm using OS X 10.11.

I expect that -std=c++11 is set through CMAKE_CXX_FLAGS.

**Comment by mkae** [comment]
Thanks very much, that solved it here on my 10.10! :-)

This issue can be closed thus! :+1:
